version: '3.9'

services:
  auth_service:
    image: auth_service_image:latest
    container_name: auth_service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8000"
    

  